### ISSUE TITLE
robot assembly examples

### ISSUE THREAD

**Issue by kathrindoerfler** [augmentedfabricationlab/ur_online_control#1]
Only two examples necessary:

- Setup with one robot: tower assembly example, (be careful, assembly should be in Rhino Origin Frame, and Robot should be in moved in reference to the origin frame, this needs to be changed in the current example file.
- Setup with two robots: tower assembly example, where two robots are building the tower

In both examples, one should be able to visualize the trajectory (element.trajectory), plus the end target frame (element.gripping_frame).

**Comment by gidodielemans** [comment]
These two examples have been made, additional repository for examples has been created by @lidiatanasova. Hareth Ferhat's project has been rewritten and included in this repository with a one robot setup.
